name: Dependency Security Testing

on:
  pull_request:
    branches: [ "main", "release/**" ]
    types: [ "ready_for_review" ]

jobs:
  scanning:
    uses: callmegreg-demo-org/central-security-repo/.github/workflows/dependency-review.yml@main
